require('packer-config')
require('colorschemes-config.nightfox')
require('nvim-tree-config')
require('treesitter-config')
require('orgmode-config')
require('lsp-config.language-servers')
require('telescope-config')
require('lualine-config')
require('preview-config')
require('settings')
require('mappings')
-- require('hologram-config')
